data Tipo
      = Bug
      | Dark
      | Dragon
      | Electric
      | Fighting
      | Fire
      | Flying
      | Ghost
      | Grass
      | Ground
      | Ice
      | Normal
      | Poison
      | Psychic
      | Rock
      | Steel
      | Water
      deriving (Bounded, Eq, Enum, Read, Show)